---
title: dementor writes
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
permalink: "/writes/:title"
name: Writing
description: life and times of a living dementor
google_verification: 
include:
- ".htaccess"
exclude:
- README.md
sass:
  style: compressed
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
